# Generated by Django 4.2.5 on 2023-12-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='events/default-event.jpg', null=True, upload_to='events'),
        ),
    ]
