# Generated by Django 4.2.5 on 2023-12-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_is_active_remove_review_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
