# Generated by Django 4.2.5 on 2023-12-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
        migrations.AddField(
            model_name='event',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
