# Generated by Django 4.2.5 on 2023-12-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_is_active_event_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_reviews',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
