name: CI/CD for Django

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: "False"
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.4"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Run Django migrations
        run: python manage.py makemigrations

      - name: Run Django migrations1
        run: python manage.py migrate

      - name: Run Django tests
        run: python manage.py test

      

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.REMOTE_TARGET }}

      - name: Run Gunicorn via SSH
        run: |
          touch key.pem
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem
          ssh -i key.pem ${{secrets.USERNAME}}@${{secrets.HOST_DNS}} -p 22 '
            cd /home/ec2-user/maps-service/
            kill $(lsof -t -i:8000)
            pip install -r /home/ec2-user/maps-service/requirements.txt
            gunicorn root.wsgi:application -D
          '
        env:
          DJANGO_SETTINGS_MODULE: "root.settings"
